# name
name: Deploy GitHub Pages

# 触发条件
on:
  push:
    branches:
      - main

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.20.0]

    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'main'
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}

      # 生成静态文件
      - name: Build
        run: npm install && npm run build

      # 部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: pages # 部署到 pages 分支
          FOLDER: docs/.vuepress/dist # vuepress 生成的静态文件存放的地方
